"""Add financial tracking to orders

Revision ID: 6fc96bfa337e
Revises: bc0c79be036c
Create Date: 2026-03-16 18:27:17.581214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc96bfa337e'
down_revision = 'bc0c79be036c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('advance_payment', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('advance_payment')
        batch_op.drop_column('tax_amount')

    # ### end Alembic commands ###
