"""add title and has_design to orders

Revision ID: 7a6abfb2b273
Revises: 4c50145b58f1
Create Date: 2026-03-13 13:36:24.322949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6abfb2b273'
down_revision = '4c50145b58f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('has_design', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('has_design')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
