"""add fields to products

Revision ID: b6a2b22f61c9
Revises: 1d145550bbb2
Create Date: 2026-03-13 15:32:59.500769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a2b22f61c9'
down_revision = '1d145550bbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('unit_measure', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('has_tax', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('image_path')
        batch_op.drop_column('has_tax')
        batch_op.drop_column('unit_measure')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
