"""add discount fields

Revision ID: cd62d5c319d9
Revises: b6a2b22f61c9
Create Date: 2026-03-13 16:41:32.268933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd62d5c319d9'
down_revision = 'b6a2b22f61c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_applied', sa.Boolean(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_qty_discount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('min_qty_discount')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('subtotal_amount')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('discount_applied')

    # ### end Alembic commands ###
